language: java
script:
  - EXECUTOR_PATH="/usr/local/bin/enrique" mvn clean test jacoco:report coveralls:report
jdk:
  - oraclejdk8
notifications:
  slack:
    rooms:
      - mesos-magellan:5PrTLK3anCkczFrY3mBXHrGY#general
after_success:
  - mvn clean test jacoco:report coveralls:report
